### PR TITLE
uri encoding primitives

### PR DESCRIPTION
**Pull request by fisx**
Obsoletes #7.

(I couldn't re-open the PR, hope this is what you expected.)

### CODE REVIEW

**Comment by paf31** [comment]
:+1: Looks great, thanks very much!

**Comment by paf31** [comment]
Oh, how about `decodeURIComponent`?

**Comment by fisx** [comment]
I was assuming that didn't exist because it wasn't in your list.  I should get away from the keyboard...  (-:

Fix will be here in a moment!

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
